; CY7C67200/CY7C67300 key constants seed.
.equ CPU_FLAGS_REG,      0xC000
.equ BANK_REG,           0xC002
.equ HW_REV_REG,         0xC004
.equ CPU_SPEED_REG,      0xC008
.equ POWER_CTL_REG,      0xC00A
.equ IRQ_EN_REG,         0xC00E
.equ XMEM_CTL_REG,       0xC03A
.equ HPI_IRQ_ROUTING_REG,0x0142
.equ HPI_SIE1_MSG_ADR,   0x0144
.equ HPI_SIE2_MSG_ADR,   0x0148
.equ COMM_CODE_ADDR,     0x01BC
.equ COMM_INT_NUM,       0x01C2
.equ COMM_R0,            0x01C4
