from __future__ import annotations

import argparse
import re
from pathlib import Path

HEADER = "; generated by cy16-cc-mini bootstrap compiler\n.section .text\n"


def compile_c_to_asm(source: str) -> str:
    """Very small smoke-test compiler, not the final chibicc backend.

    Supported forms:
      uint16_t name(void) { return 0x1234; }
      uint16_t read_hwrev(void) { return *(volatile uint16_t *)0xC004; }
    """
    out = [HEADER]
    func_re = re.compile(r'(?:uint16_t|unsigned\s+short|unsigned)\s+(\w+)\s*\(([^)]*)\)\s*\{(?P<body>.*?)\}', re.S)
    found = False
    for m in func_re.finditer(source):
        found = True
        name = m.group(1)
        body = m.group('body')
        out.append(f".global _{name}\n_{name}:\n")
        mmio = re.search(r'return\s+\*\s*\(\s*volatile\s+uint16_t\s*\*\s*\)\s*(0x[0-9a-fA-F]+|\d+)\s*;', body)
        const = re.search(r'return\s+(0x[0-9a-fA-F]+|\d+)\s*;', body)
        if mmio:
            addr = int(mmio.group(1), 0)
            # Full encoding for mov r0,[addr] is not in the bootstrap assembler yet;
            # emit a directive marker so agents can wire this into backend tests.
            out.append(f"    ; TODO cy16 backend: mov r0, [0x{addr:04x}]\n")
            out.append("    .word 0x0000\n")
        elif const:
            value = int(const.group(1), 0) & 0xFFFF
            out.append(f"    ; TODO cy16 backend: mov r0, 0x{value:04x}\n")
            out.append(f"    .word 0x{value:04x}\n")
        else:
            raise SystemExit(f"unsupported function body in {name}; use chibicc backend for real work")
        out.append("    ret\n\n")
    if not found:
        raise SystemExit("no supported uint16_t functions found")
    return ''.join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description='Tiny placeholder C-to-CY16-asm compiler smoke tool')
    ap.add_argument('-S', action='store_true', help='emit assembly')
    ap.add_argument('input')
    ap.add_argument('-o', '--output', required=True)
    args = ap.parse_args(argv)
    if not args.S:
        raise SystemExit('cy16-cc-mini only supports -S')
    asm = compile_c_to_asm(Path(args.input).read_text(encoding='utf-8'))
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(asm, encoding='utf-8')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
